replace wl_colpick with 01micko's new, yad-based implementation
https://gist.github.com/01micko/0df689bce9b4df80d839e206adfae80d

Co-authored-by: Mick Amadio <01micko@gmail.com>

diff --git a/woof-code/rootfs-skeleton/usr/bin/wl_colpick b/woof-code/rootfs-skeleton/usr/bin/wl_colpick
--- a/woof-code/rootfs-skeleton/usr/bin/wl_colpick
+++ b/woof-code/rootfs-skeleton/usr/bin/wl_colpick
@@ -1,74 +1,67 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# wl_colpick
+# (c) Copyright 2024 Mick Amadio <01micko@gmail.com> GPL3
+# requires yad, sed, grep, dc, ppmtoxpm, grim, slurp 
 
-# requires grim, slurp, netpbm, grep, sed
-# GPLv2
+# simple hex to decimal conversion
+find_color() {
+    printf "%d" "0x${1}"
+}
 
-# choice GUI
-export CGUI='<window title="Color Picker" resizable="false">
-	<vbox>
-		<hbox space-expand="true" space-fill="true">
-			<text>
-				<label>Click the place on screen where you want to fetch the color</label>
-			</text>
-			<button image-position="2">
-				<height>40</height>
-				<input file icon="select-color"></input>
-				<action>exit:SCREEN</action>
-			</button>
-		</hbox>
-		<hseparator></hseparator>
-			<text use-markup="true">
-				<label>"<big>OR</big>"</label>
-			</text>
-		<hseparator></hseparator>
-		<hbox space-expand="true" space-fill="true">
-			<text>
-				<label>Choose a color from the color button palette</label>
-			</text>
-			<colorbutton>
-				<default>#FF00FF</default>
-				<variable>CHOSEN</variable>
-			</colorbutton>
-		</hbox>
-		<hseparator></hseparator>
-		<hbox>
-			<button ok></button>
-		</hbox>
-	</vbox>
-</window>'
+# uses pnmtoxpm to make a 1px xpm image
+get_col() {
+    col=$(pos="$(slurp -b FFFFFF00 -p)";sleep 1; grim -g "$pos" -t ppm - | ppmtoxpm | grep -m1 '" c.*"' | sed -e 's/\" c //' -e 's/\".*$//')
+    echo $col
+}
 
-eval $(gtkdialog -p CGUI)
+# shows our selected hex, rgb() and float notation colors
+return_gui() {
+    echo -e '<?xml version="1.0" encoding="UTF-8"?>
+<svg xmlns="http://www.w3.org/2000/svg" version="1.1"  height="48px" width="48px" viewBox="0 0 48 48">
+  <path d="m 0 0 48 0 0 48 -48 0 z" style="fill:'$1';stroke:none;"/>
+</svg>' > $TEMPDIR/col.svg
+    BCOL=${1/\#/}
+    BR=${BCOL:0:2}; BG=${BCOL:2:2}; BB=${BCOL:4:2};
+    BHR=$(find_color $BR)
+    BHG=$(find_color $BG)
+    BHB=$(find_color $BB)
+    ZC='rgb('$BHR','$BHG','$BHB')'
+    BHR=$(dc -e'3k '$BHR' 255 / p')
+    BHG=$(dc -e'3k '$BHG' 255 / p')
+    BHB=$(dc -e'3k '$BHB' 255 / p')
+    X=''
+    [[ ${BHR:0:1} = '.' ]] && X=0
+    [[ ${BHG:0:1} = '.' ]] && X=0
+    [[ ${BHB:0:1} = '.' ]] && X=0
+    ZF=''$X$BHR' '$X$BHG' '$X$BHB''
+    yad --title="Color Picker" --name="select-color" --form \
+    --image="$TEMPDIR/col.svg" --text=" Copy and paste color found\n to your application:" \
+    --field="Color Hex" "$1" \
+    --field="Color rgb" "$ZC" \
+    --field="Color float" "$ZF" \
+    --button="Ok!gtk-ok":0
+}
 
-case $EXIT in
-	# needs sleep, dunno why
-	SCREEN)C=$(pos="$(slurp -b FFFFFF00 -p)";sleep 1; grim -g "$pos" -t ppm - | ppmtoxpm | grep -m1 '\" c.*\"' | sed -e 's/\" c //' -e 's/\".*$//')
-	;;
-	OK)C=$CHOSEN;;
-	*)exit;;
-esac
+export -f find_color get_col return_gui
 
-# bg color
-echo 'window {
- background-color:'$C';
-}' > /tmp/wl_colpick.css
+# this script is wayland dependant
+[[ -n "$WAYLAND_DISPLAY" ]] || {
+    yad --title=error --window-icon="dialog-error" --name="dialog-error" \
+      --text="Error: This applicatiom <b>must</b> be run in a wayland session." \
+      --button="Close!dialog-error":1
+    exit 1
+}
 
-case "$C" in
-	*1*1*1*)ISITOK='Is this color OK? Sometimes this app fails but you can try again.';; # eg #151617
-esac
+export TEMPDIR
+TEMPDIR=$(mktemp -d /tmp/colpickXXXX)
 
-# return GUI
-echo '<window title="Color Picker" resizable="false" height-request="180" width-request="300">
-	<vbox>
-		<hbox>
-			<text use-markup="true" max-width-chars="50"><label>"<span background='"'#BBBBBB'"'>Select and copy/paste the color string below. '$ISITOK'</span>"</label></text>
-		</hbox>	
-		<hbox space-expand="true" space-fill="true">	
-			<text selectable="true" use-markup="true"><label>"<big><big>'$C'</big></big>"</label></text>
-		</hbox>
-		<hbox>	
-			<button ok></button>
-		</hbox>
-	</vbox>
-</window>' | gtkdialog -s --styles=/tmp/wl_colpick.css >/dev/null 2>&1
+# cleanup
+trap "rm -rf $TEMPDIR" EXIT
+
+# main gui
+ret=$(yad --title="Color Picker" --window-icon="select-color" --name="select-color" \
+    --text="Click the Select button then place the cursor \n on screen where you want to fetch the color" \
+    --buttons-layout=center \
+    --button="Select!preferences-desktop-cursors!choose place on screen":'bash -c "get_col && kill -USR1 $YAD_PID"')
+[[ $? -ne 0 ]] && exit
+return_gui $ret
