fix breakage of initrd

diff --git a/initrd-progs/0initrd/init b/initrd-progs/0initrd/init
--- a/initrd-progs/0initrd/init
+++ b/initrd-progs/0initrd/init
@@ -169,11 +169,7 @@ ensure_mounted() {
    fsck_func /dev/${1} $ONE_FS
  fi
  /sbin/mountpartition /dev/${1} $ONE_MP $ONE_FS #-t $ONE_FS /dev/$ONE_PART $ONE_MP
- if [ $? -ne 0 ] ; then
-  sleep 3 # usb optical drive showing as /sys/block/sr0, but won't mount, needs more delay...
-  /sbin/mountpartition /dev/${1} $ONE_MP $ONE_FS
-  [ $? -ne 0 ] && { echo "${1} on $ONE_MP as $ONE_FS mount failed."; ONE_MP=""; return 1; }
- fi
+ [ $? -ne 0 ] && { echo "${1} on $ONE_MP as $ONE_FS mount failed."; ONE_MP=""; return 1; }
 }
 
 ensure_save_mounted() {
@@ -387,21 +383,19 @@ search_func() {
     if [ "$PUP_SAVES" ];then
      SAVEPART="$ONE_PART"
      LOOK_SAVE=""
-     [ "$LOOK_PUP" ] || return
     fi
    fi
    if [ "$LOOK_PUP" ];then
-    find_drv_file /mnt/pdrv "$DISTRO_PUPPYSFS" ""
+    find_drv_file "$ONE_MP" "$DISTRO_PUPPYSFS" ""
     if [ "$ONE_SFS" ];then
      PDRV_SFS="$ONE_SFS"
      P_PART="$ONE_PART"
      DEV1FS="$ONE_FS"
      LOOK_PUP=""
-     [ "$LOOK_SAVE" ] || return
-     continue
     fi
    fi
    umount $ONE_MP
+   [ "$LOOK_PUP" -o "$LOOK_SAVE" ] || break
   fi
  done < <(lsblk -rno type,name | grep ^part | cut -f 2 -d ' ')
 }
@@ -512,10 +506,11 @@ if [ "$LOOK_PUP" -o "$LOOK_SAVE" ];then #something to search for
   NUM=$(($NUM + 1))
  done
 fi
-[ "$P_BP_ID" ] && { log_part_id "$P_BP_ID"; ONE_PART="$P_BP_ID"; }
+[ "$P_BP_ID" ] && log_part_id "$P_BP_ID"
 if [ "$PDRV_SFS" = "" ];then
  fatal_error "$DISTRO_PUPPYSFS not found." "Finding puppy main sfs file."
 fi
+ensure_mounted "$P_PART" "/mnt/pdrv"
 
 #establish SAVEPART
 decode_id "$SAVE_BP_ID"
